pipeline {
    agent any

    tools {
        // استخدام Python 3 (ممكن تغيّر حسب النسخة المثبتة عندك)
        python "Python3"
    }

    stages {
        stage('Checkout') {
            steps {
                // اسحب الكود من GitHub (الريبو لازم يكون مربوط بالكريدنشلز)
                git branch: 'main',
                    credentialsId: '44b6510e-c45a-4248-8df7-e43c0f8451f5',
                    url: 'https://github.com/reemelfadilhassanin/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    cd messaging_app
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    cd messaging_app
                    . venv/bin/activate
                    pytest --maxfail=1 --disable-warnings -q --junitxml=report.xml
                '''
            }
            post {
                always {
                    junit 'messaging_app/report.xml'
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished!"
        }
        failure {
            echo "Pipeline failed ❌"
        }
        success {
            echo "Pipeline succeeded ✅"
        }
    }
}
