pipeline {
    agent any

    tools {
        python 'Python3' // Set this up in ShiningPanda later
    }

    environment {
        GITHUB_CREDENTIALS = credentials('44b6510e-c45a-4248-8df7-e43c0f8451f5') // Use your actual ID
    }

    stages {
        stage('Clone repository') {
            steps {
                git credentialsId: "${GITHUB_CREDENTIALS}", url: 'https://github.com/reemelfadilhassanin/alx-backend-python.git'
            }
        }

        stage('Setup Python Environment') {
            steps {
                withPythonEnv('Python3') {
                    sh 'pip install -r messaging_app/requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                withPythonEnv('Python3') {
                    sh 'pytest messaging_app/tests/ --junitxml=report.xml'
                }
            }
        }

        stage('Publish Report') {
            steps {
                junit 'report.xml'
            }
        }
    }
}
