pipeline {
    agent any

    environment {
        GIT_CREDENTIALS_ID = 'github-creds'
    }

    stages {
        stage('Clone repository') {
            steps {
                git credentialsId: "${GIT_CREDENTIALS_ID}", url: 'https://github.com/YOUR_USERNAME/alx-backend-python.git'
            }
        }

        stage('Install dependencies and run tests') {
            steps {
                sh '''
                cd messaging_app
                python3 -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
                pytest --junitxml=test-report.xml
                '''
            }
        }

        stage('Archive Test Results') {
            steps {
                junit 'messaging_app/test-report.xml'
            }
        }
    }
}
        stage('Build Docker Image') {
            steps {
                sh '''
                cd messaging_app
                docker build -t yourdockerhubusername/messaging_app:latest .
                '''
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker push yourdockerhubusername/messaging_app:latest
                    '''
                }
            }
        }
