#!/bin/bash
set -e

echo "🚀 Deploying Blue Version..."
kubectl apply -f blue_deployment.yaml

echo "🚀 Deploying Green Version..."
kubectl apply -f green_deployment.yaml

echo "🔍 Checking logs for Green Deployment..."
POD=$(kubectl get pods -l app=django,version=green -o jsonpath='{.items[0].metadata.name}')
kubectl logs -f $POD
